# -*- coding: utf-8 -*-
"""Simple Projects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5gPlydVJDwgPW9n9bZxLwQFqE1YrKYb
"""

import string
import random

lowercase_letters = list(string.ascii_lowercase)
uppercase_letters = list(string.ascii_uppercase)
numbers = list(string.digits)
others = list(string.punctuation)
all_values = lowercase_letters + uppercase_letters + numbers + others
password = ""
password_length = int(input("How long do you want your password to be? "))
while len(password) < password_length:
    password = random.choice(all_values) + str(password)
print(password)

#0\l"Ck7Z
#7q_8UxEeB9N%

import string
import random

lowercase_count = int(input("How many lowercase letters do you want? "))
uppercase_count = int(input("How many uppercase letters do you want? "))
number_count = int(input("How many numbers do you want? "))
special_count = int(input("How many special characters do you want? "))

def lowercase_amount(lowercase_count):
  lowercase_letters = list(string.ascii_lowercase)
  lowercase_password = ""
  while len(lowercase_password) < lowercase_count:
    lowercase_password = random.choice(lowercase_letters) + str(lowercase_password)
  return lowercase_password

def uppercase_amount(uppercase_count):
  uppercase_letters = list(string.ascii_uppercase)
  uppercase_password = ""
  while len(uppercase_password) < uppercase_count:
    uppercase_password = random.choice(uppercase_letters) + str(uppercase_password)
  return uppercase_password

def number_amount(number_count):
  numbers = list(string.digits)
  numbers_password = ""
  while len(numbers_password) < number_count:
    numbers_password = random.choice(numbers) + str(numbers_password)
  return numbers_password

def special_amount(special_count):
  others = list(string.punctuation)
  others_password = ""
  while len(others_password) < special_count:
    others_password = random.choice(others) + str(others_password)
  return others_password


all_values = lowercase_amount(lowercase_count) + uppercase_amount(uppercase_count) + number_amount(number_count) + special_amount(special_count)

all_values = list(all_values)
random.shuffle(all_values)
long_password = "".join(all_values)

print(long_password)